export const STORE_PRODUCTS = "STORE_PRODUCTS";
export const STORE_PAGINATION = "STORE_PAGINATION";
export const STORE_TOKEN = "STORE_TOKEN";
export const LOGOUT = "LOGOUT";
// export const GET_PRODUCTS_SUCCEESS = "GET_PRODUCTS_SUCCEESS";
// export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL ";
